const assert=require('node:assert/strict'),F=require('./fem-viewer.js');
assert.deepEqual(F.project([10,20,30],{yaw:0,pitch:0}),[10,-30,20]);
const cases=[{version:'v1',rhsThickness:1.6,loadCase:'D',status:'solved'},{version:'v2',rhsThickness:2.3,loadCase:'L',status:'unstable'}];
assert.equal(F.caseFor(cases,'v1',1.6,'D'),cases[0]);assert.equal(F.caseFor(cases,'v2',1.6,'D'),null);assert.equal(F.solved(cases[1]),false);assert.equal(F.solved(null),false);assert.equal(F.solved(cases[0]),true);
assert.equal(F.force({memberForces:{b:{N:-100}}},'b','N'),-100);assert.equal(F.force({},'b','N'),null);assert.notEqual(F.color(-100,100),F.color(100,100));assert.equal(F.segmentDistance([5,3],[0,0],[10,0]),3);assert.equal(F.segmentDistance([12,0],[0,0],[10,0]),2);
console.log('FEM viewer: projection, case isolation, failure gating, signed force, picking PASS');
(async()=>{
 const unit={status:'solved',displacements:{a:[1,-2,3,.1,.2,.3]},reactions:{a:[100,-200,300,4000,-5000,6000]},loads:{a:[1,2,3,4,5,6]},memberForces:{b:{N:-12,Vy:3,Vz:4,T:500,My:-600,Mz:700,i:[1,2,3,4,5,6],j:[-1,-2,-3,-4,-5,-6]}}};
 const scaled=F.hydrate({status:'solved',resultScale:6.5,summary:{value:10}},unit);assert.equal(scaled.memberForces.b.My,-3900);assert.deepEqual(scaled.memberForces.b.j,[-6.5,-13,-19.5,-26,-32.5,-39]);assert.equal(scaled.reactions.a[4],-32500);assert.equal(scaled.loads.a[2],19.5);assert.equal(scaled.displacements.a[0],6.5);assert.equal(scaled.summary.value,10);assert.equal(unit.memberForces.b.My,-600);assert.equal(F.solved(F.hydrate({status:'unstable',resultScale:2},unit)),false);assert.equal(F.solved(F.hydrate({status:'solved',resultScale:2},{status:'failed'})),false);
 let calls=0;const loader=F.cachedLoader(async key=>{calls++;return key;});assert.deepEqual(await Promise.all([loader('a'),loader('a')]),['a','a']);assert.equal(calls,1);const guard=F.raceGuard(),first=guard.next(),last=guard.next();assert.equal(guard.current(first),false);assert.equal(guard.current(last),true);
 const fs=require('node:fs'),z=require('node:zlib'),path=require('node:path'),base=path.resolve('../boq-tribun-metta');if(fs.existsSync(path.join(base,'assets/fem/results.json'))){const r=JSON.parse(fs.readFileSync(path.join(base,'assets/fem/results.json'),'utf8'));for(const c of r.cases){const u=JSON.parse(z.gunzipSync(fs.readFileSync(path.join(base,r.solutions[c.solutionId].url))));const out=F.hydrate(c,u);assert(F.solved(out));const max=Math.max(...Object.values(out.displacements).map(a=>Math.hypot(...a.slice(0,3))));assert(Math.abs(max-c.summary.maxDisplacementMm)<1e-6);}assert.equal(r.cases.length,24);console.log('Actual 24 cases hydrate and maximum displacement reconciliation PASS');}
 console.log('FEM hydration scaling, failed unit gating, cache deduplication and stale-response guard PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
