"""Reference-led gallery experience layered over the retained BOQ application."""
import json,html
from pathlib import Path
from bs4 import BeautifulSoup
ROOT=Path(__file__).parent

def enhance(s):
 main=s.select_one('main')
 for selector in ['.intro','.facts-new','.mast','.new-foot']:
  for n in s.select(selector):n.decompose()
 sheets=json.loads((ROOT/'assets/technical/manifest.json').read_text(encoding='utf8'))
 calc=json.loads((ROOT/'assets/technical/perhitungan-studi.json').read_text())
 cards=''.join(f'''<article class="drawing-card" data-category="{r['category']}" id="{r['code']}"><button class="drawing-open" data-drawing="{i}" aria-label="Buka {r['code']} {r['title']}"><img src="{r['svg']}" alt="{r['code']} — {r['title']}" width="1191" height="842" {'loading="lazy"' if i else 'fetchpriority="high"'}></button><div class="drawing-caption"><span>{r['code']}</span><h3>{r['title']}</h3><span>({r['category']})</span></div></article>''' for i,r in enumerate(sheets))
 nav=''.join(f'<a href="#{r["code"]}" data-index="{i}">{i+1:02}</a>' for i,r in enumerate(sheets))
 gallery=f'''<header class="look-mast"><a href="#gambar" class="look-brand">METTA<span>®</span></a><a href="#gambar">THE BUILD / R02</a><nav aria-label="Navigasi utama"><a href="#gambar">Gambar</a><a href="#tiga-d">3D</a><a href="#boq">BOQ</a><a href="#kajian">Hitungan</a><a href="#material">Material</a></nav></header>
 <section class="look-gallery" id="gambar" aria-labelledby="gallery-title"><div class="look-title"><h1 id="gallery-title">THE<br><span>BUILD.</span></h1><div class="look-meta">METTA / TRIBUN LT 04<br>DEK BORDES 4 MM<br>12 LEMBAR · R02 / 2026<br><span class="look-status">STUDI KOORDINASI</span></div></div><div class="gallery-toolbar"><p>Gambar teknik <span id="gallery-count">(12)</span></p><div class="gallery-filters" role="group" aria-label="Filter gambar"><button data-filter="Semua" aria-pressed="true">Semua</button><button data-filter="Denah" aria-pressed="false">Denah</button><button data-filter="Potongan" aria-pressed="false">Potongan</button><button data-filter="Detail" aria-pressed="false">Detail</button></div><div class="gallery-arrows"><button id="gallery-prev" aria-label="Gambar sebelumnya">←</button><button id="gallery-next" aria-label="Gambar berikutnya">→</button></div></div><div class="drawing-track" tabindex="0" aria-label="Galeri gambar; gulir horizontal atau gunakan tombol panah">{cards}</div><div class="drawing-index"><span>INDEKS /</span>{nav}<a href="assets/technical/METTA-R02-gambar-koordinasi.pdf" target="_blank" rel="noopener">PDF ↗</a><a href="assets/technical/METTA-R02-DXF.zip" download>DXF ↓</a></div></section>
 <div class="project-strip"><span>17,70 × 5,00 M</span><span>80 TUMPUAN</span><span>8 BRACING X</span><span>82,35 M² DEK</span><a href="#tiga-d">MASUK KE MODEL ↓</a></div>'''
 main.insert(0,BeautifulSoup(gallery,'html.parser'))
 s.select_one('.drawing-track').insert_before(BeautifulSoup('<p class="gallery-help">R03 · LOD 200 · Dimensi dalam mm. Klik gambar untuk menggeser dan memperbesar.</p>','html.parser'))
 for caption in s.select('.drawing-caption'):
  caption.select('span')[-1].string+=' · LOD 200'
 s.select_one('.look-meta').clear()
 s.select_one('.look-meta').append(BeautifulSoup('METTA / TRIBUN LT 04<br>DEK BORDES 4 MM<br>12 LEMBAR · R03 / 2026<br><span class="look-status">DIMENSI / LOD 200</span>','html.parser'))
 rows=''.join(f'<tr><td>{r["span_mm"]:g} mm</td><td>{r["stress_MPa"]:.2f}</td><td>{r["deflection_mm"]:.3f}</td><td>{r["L360_mm"]:.3f}</td><td>{"Lolos penyaringan" if r["pass_screen"] else "Tidak lolos lendutan"}</td></tr>' for r in calc['deck'])
 study=f'''<section class="block technical-study" id="kajian"><p class="eyebrow">04 / DESIGN BASIS</p><h2>Lebih tipis.<br>Tumpuan lebih rapat.</h2><p class="lede">Studi mempertahankan dek 4 mm dengan target penyangga 250 mm dan satu profil utama RHS 50 × 100 × 2,3 mm. Jarak 333 mm berada dekat batas lendutan; 500 mm tidak lolos penyaringan ini. Pilihan 250 mm memberi ruang terhadap variasi tebal, tetapi beban titik dan getaran masih harus dihitung.</p><div class="tw"><table><thead><tr><th>Jarak penyangga</th><th>Tegangan (MPa)</th><th>Lendutan (mm)</th><th>Batas L/360 (mm)</th><th>Hasil terbatas</th></tr></thead><tbody>{rows}</tbody></table></div><div class="study-notes"><p><b>Model hitungan</b><br>Strip baja 1 m, dua tumpuan sederhana. E = 200.000 MPa; Fy = 240 MPa asumsi. D = 1,20 kPa dan L = 4,79 kPa sebagai input pembanding. qᵤ = 1,2D + 1,6L. Kategori beban SNI belum dikunci.</p><p><b>Yang dapat dibandingkan</b><br>Massa dasar dek 4 mm ≈ {calc['deck_base_mass_kg']:,.0f} kg; penurunan dari 8 mm ≈ {calc['deck_mass_reduction_kg']:,.0f} kg pada luas sama. Ini belum penghematan total karena tambahan rangka, sambungan dan pekerjaan.</p><p><b>Yang belum terbukti</b><br>Beban titik, getaran, tekuk lokal hollow, sambungan, geser/angkat dudukan, kapasitas beton LT4, gempa dan jalur evakuasi. Tidak ada klaim lulus SNI atau izin fabrikasi.</p></div><details><summary>Acuan dan rumus yang digunakan</summary><p>M = qL²/8; σ = M/S; δ = 5qL⁴/(384EI), I = bt³/12. Batas tegangan penyaringan 0,9Fy dan lendutan L/360. Rumus ini tidak menggantikan analisis rangka tiga dimensi.</p><ul><li><a href="https://pesta.bsn.go.id/produk/detail/12927-sni17272020" target="_blank" rel="noopener">SNI 1727:2020 — penetapan beban</a></li><li><a href="https://pesta.bsn.go.id/produk/index/219" target="_blank" rel="noopener">SNI 1729:2020 — struktur baja, adopsi ANSI/AISC 360-16</a></li><li><a href="https://pesta.bsn.go.id/produk/by_ics?ics_no=91.080&amp;key=" target="_blank" rel="noopener">Katalog BSN — SNI 7971:2013 dan SNI 1726:2019</a>; pilih standar material yang sesuai produk sebenarnya.</li></ul><p>Daftar acuan bukan bukti pemeriksaan seluruh pasal. Beton dan angkur memerlukan acuan beton yang berlaku serta data tulangan proyek.</p><a href="assets/technical/perhitungan-studi.json" download>Unduh input dan hasil hitungan ↓</a></details></section>'''
 sources='''<section class="block" id="material"><p class="eyebrow">05 / LOCAL SOURCING</p><h2>Dari Surabaya.<br>Dengan sumber jelas.</h2><p class="lede">Harga katalog diperiksa 7 September 2026. Bukan penawaran resmi atau jaminan stok. Mutu, tebal dasar, toleransi, ongkir dan sertifikat per lot perlu dikonfirmasi sebelum pembelian.</p><div class="material-grid"><article><span>01 / DEK</span><h3>Bordes 4 mm</h3><p>1.200 × 2.400 mm<br>Duta Merpati · Merr, Surabaya</p><b>Rp1.273.000 / lembar</b><p>Harga publik termasuk PPN menurut halaman pemasok. Minimum luas: 29 lembar untuk 82,35 m²; jumlah ini belum mencakup pola potong dan tidak boleh langsung dipesan.</p><a href="https://dutamerpati.com/distributor/plat-bordes-40mm-1200x-2400-surabaya" target="_blank" rel="noopener">Sumber katalog ↗</a></article><article><span>02 / RANGKA</span><h3>RHS 50 × 100 × 2,3</h3><p>Stok 6 m · 32,5 kg/batang<br>SMS Perkasa · Tambak Langon</p><b>Rp434.500 / batang</b><p>75 batang rangka = Rp32.587.500 sebagai pembanding material. Belum termasuk kolom, railing, sambungan, fabrikasi dan pengiriman. Harga katalog termasuk PPN.</p><a href="https://www.smsperkasa.com/produk/besi-hollow-hitam" target="_blank" rel="noopener">Sumber katalog ↗</a></article><article><span>03 / OPSI DINDING TEBAL</span><h3>RHS 50 × 100 × 3,2</h3><p>Stok 6 m · 45,22 kg/batang<br>SMS Perkasa · Surabaya</p><b>Rp603.700 / batang</b><p>Opsi pembanding untuk area sambungan atau kolom. Belum dipilih: kekuatan, jumlah batang dan jam kerja harus dibandingkan sebelum mengubah model.</p><a href="https://www.smsperkasa.com/produk/besi-hollow-hitam" target="_blank" rel="noopener">Sumber katalog ↗</a></article></div></section>'''
 process='''<section class="block" id="pelaksanaan"><p class="eyebrow">06 / ASSEMBLY</p><h2>Satu urutan.<br>Lebih sedikit pekerjaan ulang.</h2><ol class="assembly-list"><li><b>01 / Survei & tandai</b><span>Cocokkan elevasi LT4, titik beton, bukaan tangga dan 80 posisi dudukan. Selesaikan desain sambungan sebelum memotong.</span></li><li><b>02 / Potong & beri kode</b><span>Gunakan daftar 75 stok hanya untuk 161 RHS studi. Kelompokkan potongan per bay, ukur kerf, dan simpan sisa menurut panjang.</span></li><li><b>03 / Rakit modul di jig</b><span>Samakan satu profil dan orientasi tinggi 100 mm. Periksa diagonal modul dan gunakan urutan las untuk membatasi distorsi.</span></li><li><b>04 / Pasang rangka & X</b><span>Mulai dari dudukan, kolom, balok, lalu X. Pasang penyangga sementara dan ikatan beton sesuai detail yang telah diperiksa.</span></li><li><b>05 / Dek & pelengkap</b><span>Tumpukan sambungan dek di atas penyangga. Pasang tangga, railing, kayu dan lapisan antikarat setelah pemeriksaan rangka.</span></li></ol><p class="lede">Pola lembar bordes harus dihitung dari panel potong dan garis tumpuan yang final. Sisa tepi dapat dialokasikan ke komponen 4 mm lain hanya jika ukuran, arah motif dan mutu sesuai.</p></section>'''
 boq=s.select_one('#boq');boq.insert_before(BeautifulSoup(study+sources+process,'html.parser'))
 s.select_one('#kajian details ul').append(BeautifulSoup('<li><a href="https://pesta.bsn.go.id/produk/detail/12731-sni28472019" target="_blank" rel="noopener">SNI 2847:2019 — beton struktural dan pemeriksaan angkur ke beton</a></li>','html.parser'))
 s.select_one('#material').append(BeautifulSoup('''<div class="material-grid"><article><span>04 / PAPAN PINUS</span><h3>CV Mekar Abadi</h3><p>Gunung Anyar Tambak, Surabaya. Mencantumkan papan pinus pada profil pemasok; ukuran 400 × 40 mm, kadar air, mutu dan harga belum dikonfirmasi.</p><a href="https://cvmekarabadi.indonetwork.co.id/info" target="_blank" rel="noopener">Profil pemasok ↗</a></article><article><span>05 / KARET DUDUKAN</span><h3>Morgan Powerindo Amerta</h3><p>Bratang Gede, Surabaya. Menawarkan neoprene dan EPDM lembaran. Tebal 10 mm, kekerasan, tekanan kerja dan ukuran potong 150 × 150 harus dikonfirmasi; bukan otomatis bantalan struktural tersertifikasi.</p><a href="https://morganpowerindo.com/rubber-sheet.php" target="_blank" rel="noopener">Katalog karet ↗</a></article><article><span>06 / PELAPIS BAJA</span><h3>Sura Baja Solusi</h3><p>Rungkut, Surabaya. Pemasok cat Hempel. Sistem primer dan lapis akhir, persiapan permukaan, ketebalan kering serta jumlah liter ditetapkan setelah luas baja dan lingkungan paparan diperiksa.</p><a href="https://www.solusihempel.id/" target="_blank" rel="noopener">Katalog pelapis ↗</a></article></div>''','html.parser'))
 s.select_one('#boq h2').string='07 / Hitung kebutuhan & biaya.'
 s.select_one('#boq').insert(2,BeautifulSoup('<p>Dasar lembar studi: <b>1.200 × 2.400 mm (2,88 m²)</b>. Jumlah lembar memakai faktor sisa, belum pola potong panel. Ukuran ini harus dikonfirmasi untuk pelat selain dek.</p><p><button id="catalog-prices">Isi harga katalog pada kolom kosong</button></p><p id="catalog-price-status" role="status">RHS Rp434.500/batang; dek Rp1.273.000/lembar. Harga katalog termasuk PPN pemasok.</p>','html.parser'))
 s.select_one('#boq').append(BeautifulSoup('''<details class="scope-register"><summary>Kelengkapan lingkup web lama dan status revisinya</summary><div class="tw"><table><thead><tr><th>Komponen</th><th>Status R02</th><th>Dasar jumlah berikutnya</th></tr></thead><tbody><tr><td>Kolom, balok, stiffener, strut, X</td><td>Jumlah rangka utama diperbarui</td><td>80 kolom + 161 framing; 8 X termasuk framing</td></tr><tr><td>Dek bordes, base plate, karet</td><td>Dek 4 mm; 80 dudukan</td><td>Area dek hasil model; potongan panel belum final</td></tr><tr><td>Riser, skirt, toe-board, tangga</td><td>Estimasi arsitektur dipertahankan dan diberi label</td><td>Ukur ulang luas bentangan termasuk tekukan</td></tr><tr><td>Railing, baluster, pinus, sandaran</td><td>Estimasi lama, skema gambar diperjelas</td><td>Kunci bukaan baluster, tinggi dan jalur evakuasi</td></tr><tr><td>Baut M12, angkur M10, gusset, pelat siku</td><td>Ukuran lama tidak ditetapkan sebagai detail revisi</td><td>Gaya sambungan, dinding RHS, mutu beton, tulangan dan jarak tepi</td></tr><tr><td>Sekrup kayu, kawat las, cat dasar/akhir, nosing</td><td>Belum masuk total revisi; bukan nol kebutuhan</td><td>Pola pemasangan, panjang las, luas permukaan dan sistem pelapisan</td></tr><tr><td>3D, 12 gambar, BOQ, penawaran, Excel/PDF</td><td>Tersedia pada web R02</td><td>Rekap harga tetap parsial sampai item yang belum dihitung lengkap</td></tr></tbody></table></div></details>''','html.parser'))
 s.select_one('#potong h2').string='08 / Daftar potong.'
 scope_rows=s.select('.scope-register tbody tr')
 scope_rows[2].select('td')[1].string='Pelat tangga diukur dari model; riser, skirt dan toe-board masih estimasi'
 scope_rows[3].select('td')[1].string='Railing, baluster dan pinus diukur dari model; sandaran masih estimasi'
 scope_rows[5].select('td')[1].string='Luas nosing diukur dari model; konsumsi dan item lainnya belum dihitung'
 s.select_one('#boq .lede').string='Kuantitas rangka, dek, railing, papan pinus, pelat tangga dan nosing mengikuti pembacaan model. Sandaran, riser dan skirt masih estimasi berlabel. Sambungan, angkur, las dan sebagian pelapisan belum masuk total; harga kosong bukan barang gratis.'
 s.select_one('#penawaran h2').string='09 / Susun penawaran.'
 review=s.select_one('.review');review.select_one('h2').string='Status desain.'
 foot='''<footer class="look-footer"><div><span>METTA / R02</span><p>GAMBAR. MODEL.<br>MATERIAL. BIAYA.</p></div><div><a href="assets/technical/METTA-R02-gambar-koordinasi.pdf" target="_blank" rel="noopener">12 lembar PDF ↗</a><a href="assets/technical/METTA-R02-DXF.zip" download>DXF editable ↓</a><a href="#revit-native">Lembar Revit ↓</a><a href="https://bambssquad.github.io/boq-tribun-metta/" target="_blank" rel="noopener">Arsip web sumber ↗</a></div><a class="back-top" href="#gambar" aria-label="Kembali ke atas">↑</a></footer>'''
 main.append(BeautifulSoup(foot,'html.parser'))
 nativefiles=sorted((ROOT/'assets/technical/revit').glob('*.png'))
 links=''.join('<a href="assets/technical/revit/'+html.escape(p.name)+'" target="_blank" rel="noopener">'+html.escape(p.stem)+' ↗</a>' for p in nativefiles)
 main.select_one('.look-footer').insert_before(BeautifulSoup('<section class="block" id="revit-native"><p class="eyebrow">10 / NATIVE REVIT</p><h2>Lembar kerja Revit.</h2><p>12 sheet M-R02-01 sampai M-R02-12 ada pada model Revit. Denah/rangka memakai proyeksi koordinasi; potongan memakai view model. Detail S-08 sampai S-11 berupa garis dan teks native. Ekspor PNG berikut untuk pemeriksaan isi; file RVT disediakan terpisah.</p><div class="native-list">'+links+'</div></section>','html.parser'))
 dialog='''<dialog id="drawing-dialog" aria-labelledby="drawing-title"><div class="dialog-bar"><h2 id="drawing-title">Gambar teknik</h2><button id="drawing-close" aria-label="Tutup gambar">Tutup ×</button></div><div class="drawing-tools" role="group" aria-label="Kontrol tampilan gambar"><button id="drawing-zoom-out" aria-label="Perkecil gambar">−</button><output id="drawing-zoom-level" aria-label="Pembesaran gambar">100%</output><button id="drawing-zoom-in" aria-label="Perbesar gambar">+</button><button id="drawing-reset">Reset tampilan</button><span id="drawing-help">Tarik untuk geser · scroll/cubit untuk zoom · klik dua kali untuk reset</span></div><div class="dialog-paper" id="drawing-viewport" tabindex="0" role="group" aria-label="Gambar interaktif; tombol panah untuk geser, plus/minus untuk zoom, nol untuk reset" aria-describedby="drawing-help"><img id="drawing-large" alt="" width="1191" height="842" draggable="false"></div><p id="drawing-note"></p><div class="dialog-actions"><button id="drawing-prev">← Sebelumnya</button><a id="drawing-dxf" download>DXF ↓</a><a id="drawing-svg" target="_blank" rel="noopener">SVG ↗</a><button id="drawing-next">Berikutnya →</button></div></dialog>'''
 main.append(BeautifulSoup(dialog,'html.parser'))
 script=s.new_tag('script');script.string='const DRAWING_DATA='+json.dumps(sheets,ensure_ascii=False)+';\n'+(ROOT/'panzoom.js').read_text(encoding='utf8')+'\n'+(ROOT/'experience.js').read_text(encoding='utf8');main.append(script)
 css=s.new_tag('style');css.string=(ROOT/'experience.css').read_text();main.append(css)
 return s
