const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {computePurchaseService}=require('./kg_pricing.js');
const rows={hollow:[{nm:'H',L:6.01,kg:5}],plate:[{nm:'P',A:2.9,t:4,sur:0}]};
const hb=r=>({bars:Math.ceil(r.L*1.05/6)}),pb=r=>({sh:Math.ceil(r.A*1.1/2.88)});
let j=computePurchaseService(rows,6,2.88,hb,pb,true,6000);
assert.ok(Math.abs(j.kg-240.864)<1e-8);assert.ok(Math.abs(j.cost-1445184)<1e-6);
assert.equal(computePurchaseService(rows,6,2.88,hb,pb,false,6000).cost,0);
assert.equal(computePurchaseService(rows,6,2.88,hb,pb,true,-10).cost,0);
assert.ok(Math.abs(computePurchaseService(rows,6,2.88,hb,pb,true,7000).cost-j.kg*7000)<1e-7);
const page=fs.readFileSync('dist/tools.html','utf8');
const DATA=JSON.parse(page.match(/const DATA = (\{.*?\});/s)[1]);
const S={rows:{hollow:DATA.hollow,plate:DATA.plate,other:DATA.other||[]},bar:6,wH:5,wP:10,ohp:10,ppn:0,mode:'satuan',unitAll:'auto',fabrication:{enabled:true,rate:6000}};
const basisH=page.match(/function basisH\(r\)\{.*?\n\}/s)[0],basisP=page.match(/function basisP\(r\)\{.*?\n\}/s)[0];
const service=page.match(/function serviceCost\(\)\{.*?\}/s)[0];
const wb=page.slice(page.indexOf('function workbook(){'),page.indexOf('\nfunction downloadXlsx'));
const defs=page.slice(page.indexOf('const UNITS='),page.indexOf('const usel='));
const context={S,DATA,computePurchaseService,XL:{S:{},book:s=>s},projName:()=> 'METTA',OF:()=>({co:{nm:'PT Contoh'},cl:{nm:'Klien',loc:'METTA'},terms:[{nm:'DP',pct:30},{nm:'Pelunasan',pct:70}]}),ofNo:()=> 'TEST/001'};
vm.createContext(context);vm.runInContext(basisH+'\n'+basisP+'\n'+service+'\n'+defs+'\n'+wb+'\nthis.job=serviceCost();this.sheets=workbook();',context);
assert.equal(context.job.items[0].units,75);assert.equal(context.job.items[0].purchaseKg,2437.5);
assert.ok(context.job.kg>context.job.netKg);
const sheet=context.sheets.find(s=>s.name==='BERAT');assert.equal(sheet.rows.length,DATA.hollow.length+DATA.plate.length+4);
const rk=context.sheets.find(s=>s.name==='REKAP');assert.match(rk.rows[6][2].f,/IF\(INPUT!B14=1,BERAT!E\d+\*INPUT!B13,0\)/);
assert.equal(rk.rows[7][2].f,'SUM(C4:C7)');assert.equal(rk.rows[11][2].f,'C10+C11');
const quote=context.sheets.find(s=>s.name==='PENAWARAN');assert.equal(quote.rows[11][1].f,'REKAP!C12');
assert.equal(quote.rows[17][2].f,'$B$12*B18/100');
fs.writeFileSync('../kg-pricing-test-data.json',JSON.stringify({job:context.job,sheets:context.sheets},null,2));
console.log(JSON.stringify({pass:true,netKg:context.job.netKg,purchaseKg:context.job.kg,serviceCost:context.job.cost,sheets:context.sheets.map(s=>s.name)}));
