"""Selected R04 offer, linked into the existing archive and technical page."""
import json,html
from pathlib import Path
from bs4 import BeautifulSoup
ROOT=Path(__file__).parent
def build(dist,data):
 def kg(value):return f'{value:,.3f}'.replace(',','_').replace('.',',').replace('_','.')
 manifest=json.loads((ROOT/'assets/r04/drawings.json').read_text())
 cards=''.join(f'<button class="drawing" data-sheet="{x["code"]}" aria-label="Buka {x["title"]}"><img src="assets/r04/{x["code"]}.svg" alt="{x["title"]}" loading="lazy"><span>{x["code"]} / {x["title"]} ↗</span></button>' for x in manifest)
 sources=''.join(f'<li><a href="{v[1]}" target="_blank" rel="noopener">{html.escape(v[0])} ↗</a></li>' for v in data['sources'].values())
 template='''<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SAP | METTA R04 — Tangga 3 mm dan RAB</title><link rel="stylesheet" href="assets/r04/style.css"></head><body>
<header><a href="index.html">SAP</a><span>METTA / R04 / 09.2026</span><nav><a href="#gambar">Gambar</a><a href="#rab">RAB</a><a href="#penawaran-r04">Penawaran</a><a href="tools.html#tiga-d">Model 3D ↗</a></nav></header>
<main><section class="intro"><p class="eyebrow">SELARAS ADHI PERKASA / USULAN TEKNIS</p><h1>TANGGA TEKUK.<br>PELAT 3 MM.</h1><p>Dek tribun tetap bordes 4 mm. Modul tangga dilas di bengkel, lalu dipasang dengan baut di lokasi. Satu revisi terpilih dengan rincian pengadaan dan biaya pekerjaan.</p><div class="metrics"><div><strong>56</strong><span>bidang tangga</span></div><div><strong>2 × 50 mm</strong><span>tekukan tepi</span></div><div><strong>≤ 75 mm</strong><span>celah bersih pengaku</span></div><div><strong>8 X</strong><span>pengaku global dipertahankan</span></div></div></section>
<section id="gambar"><p class="eyebrow">01 / GAMBAR TEKNIK DAN SAMBUNGAN</p><h2>Dimensi yang bisa diperiksa.</h2><p>Denah, potongan tapak, sambungan baut, dan bentangan potong. Buka gambar untuk geser dan zoom.</p><div class="drawings">CARDS</div><div class="downloads"><a href="assets/r04/METTA-R04-tangga-detail.pdf" target="_blank">PDF 4 lembar ↗</a><a href="assets/r04/METTA-R04-DXF.zip" download>CAD / DXF ↓</a><a href="assets/r04/potong-R04.csv" download>Daftar potong ↓</a></div></section>
<section id="analisis"><p class="eyebrow">02 / EFISIENSI DAN DASAR TEKNIS</p><h2>Optimasi pada modul dan pemotongan.</h2><div id="analysis-results" class="metrics"></div><div class="columns"><article><h3>Rangka yang berulang</h3><p>RHS 50×100×2,3 untuk rangka, kolom dan stringer modul. SHS 40×40×2 untuk pengaku tapak; bentang pengaku maksimum 800 mm. Bidang lebar 2.000 mm memakai tumpuan antara.</p></article><article><h3>Las bengkel, baut lokasi</h3><p>Usulan dua baut M12 kelas 8.8 per titik pada pelat 6 mm. Mur dan dua ring dihitung terpisah. Baut melalui kupingan eksternal, sehingga pengencangan tidak meremukkan dinding hollow.</p></article><article><h3>Biaya seluruh lingkup</h3><p>Tekukan menambah luas pelat. Selisih berat terhadap pelat datar lama kecil; tambahan penyangga dan sambungan masuk dalam revisi. Total baru tidak dibandingkan langsung dengan BOQ lama yang belum lengkap.</p></article></div><details><summary>Perhitungan, sumber kuantitas dan status pemeriksaan</summary><div id="calculation"></div><p>R04 adalah usulan koordinasi. Pemeriksaan struktur global, sambungan, getaran, beban pagar, jalur evakuasi dan kapasitas beton LT4 belum selesai. Model Revit native masih R03 karena koneksi Geopogo tidak tersedia; model web menampilkan usulan tangga R04.</p><p>Data takikan beton belum tersedia. Blank dan gambar tangga memakai batas luar geometri; lakukan kupon tekuk dan ukur bidang khusus sebelum produksi.</p><a href="assets/r04/data.json" download>Data perhitungan, nesting dan ID model ↓</a></details></section>
<section id="rab"><p class="eyebrow">03 / RAB TERURAI</p><h2>Material sampai serah terima.</h2><p>Harga satuan dapat diedit. Label “Katalog” adalah harga tayang pemasok; “Allowance” adalah angka anggaran. Pajak keluaran diatur terpisah dari harga pembelian pemasok.</p><div class="controls"><label><input id="service" type="checkbox" checked> Upah fabrikasi + pemasangan aktif</label><label>Tarif jasa / kg<input id="rate" type="number" min="0" value="6000"></label><label>Overhead %<input id="overhead" type="number" min="0" max="100" value="7"></label><label>Laba %<input id="profit" type="number" min="0" max="100" value="8"></label><label>Pajak keluaran %<input id="tax" type="number" min="0" max="100" value="0"></label></div><div class="filters" role="group" aria-label="Kategori biaya"><button data-filter="Semua" aria-pressed="true">Semua</button><button data-filter="Material" aria-pressed="false">Material</button><button data-filter="Bahan habis pakai" aria-pressed="false">Bahan habis pakai</button><button data-filter="Upah" aria-pressed="false">Upah</button><button data-filter="Peralatan dan logistik" aria-pressed="false">Alat & logistik</button></div><div class="table-wrap"><table><thead><tr><th>Kode / item</th><th>Volume</th><th>Sat.</th><th>Harga satuan (Rp)</th><th>Jumlah (Rp)</th><th>Dasar perhitungan / sumber</th></tr></thead><tbody id="rows"></tbody></table></div><p id="load-status" role="status">Memuat rincian RAB…</p></section>
<section id="penawaran-r04"><p class="eyebrow">04 / PENAWARAN ANGGARAN</p><h2>METTA — revisi terpilih R04.</h2><p>Pengadaan baja dan kayu, pembuatan modul, sambungan, antiselip, pengecatan, pengangkutan, pemasangan, serta cadangan verifikasi teknis.</p><dl id="totals"></dl><p id="offer-note"></p><div class="downloads"><button id="csv">Unduh RAB (CSV)</button><button id="json">Simpan penawaran (JSON)</button><button id="print">Cetak penawaran / PDF</button><button id="reset">Pulihkan harga dasar</button></div><p class="small">Overhead dihitung dari biaya langsung. Laba dihitung dari biaya langsung + overhead. Pajak dihitung dari nilai sebelum pajak. Default 7% / 8% / 0% adalah asumsi anggaran, bukan penetapan perpajakan. Provisional sum tetap masuk total dan disesuaikan setelah lingkupnya disahkan.</p></section>
<section id="sumber"><h2>Sumber dan pengadaan Surabaya.</h2><p>Harga tayang ditinjau 09.09.2026. Ketersediaan ukuran/produk belum merupakan reservasi stok. Angka Rp123 pada toko cat tidak dipakai sebagai harga karena tampil sebagai placeholder; biaya cat memakai allowance yang jelas.</p><ul>SOURCES</ul></section></main><footer>SAP / SELARAS ADHI PERKASA — ARSIP DESAIN METTA (09/2026)</footer>
<dialog id="drawing-dialog"><div class="dialog-head"><h2 id="sheet-title">Gambar R04</h2><button id="close">Tutup ×</button></div><div id="viewport" tabindex="0" aria-label="Gambar, geser dan zoom"><img id="sheet-image" alt="Gambar R04" draggable="false"></div><div class="downloads"><button id="minus">−</button><output id="scale">100%</output><button id="plus">+</button><button id="fit">Fit</button><a id="dxf" download>DXF ↓</a></div></dialog>
<script src="panzoom.js"></script><script src="assets/r04/app.js"></script></body></html>'''
 mass_rows=''.join(f'<tr><td>{r["code"]} / {html.escape(r["name"])}</td><td class="num">{kg(r["net_kg"])}</td><td class="num">{kg(r["purchase_kg"])}</td><td>{r["stock_qty"]:g} {r["unit"]}</td></tr>' for r in data['mass_ledger'])
 mass_html='<section id="berat"><p class="eyebrow">KUANTITAS / JEJAK BERAT</p><h2>Berat terpasang dan stok beli.</h2><p>Berat bersih berasal dari dimensi. Berat pembelian memakai massa katalog atau nominal stok. Angka berikut adalah kg, dengan tiga angka desimal; bukan hasil penimbangan pengiriman. Material sambungan dan penyangga usulan tetap diberi dasar perhitungan pada RAB.</p><div class="table-wrap"><table><thead><tr><th>Material</th><th>Bersih teoritis (kg)</th><th>Pembelian (kg)</th><th>Stok</th></tr></thead><tbody>'+mass_rows+'</tbody></table></div><p class="small">Bordes: massa motif belum tercakup. Pelat hitam katalog 4×8 kaki dipotong pada bidang pakai minimum1.200×2.400mm. Selisih berat bukan seluruhnya limbah: termasuk sisa yang dapat digunakan, margin ukuran stok dan pembulatan katalog.</p><div class="downloads"><a href="assets/r04/berat-R04.csv" download>Rincian berat CSV ↓</a></div></section>'
 template=template.replace('<section id="rab">',mass_html+'<section id="rab">')
 native_links=''.join(f'<a href="assets/r04/revit/{r["code"]}.png" target="_blank" rel="noopener">Revit {r["code"]} ↗</a>' for r in manifest)
 template=template.replace('</section>\n<section id="analisis">','<details><summary>6 lembar native Revit R04</summary><p>M-R04-T-01 sampai M-R04-T-06 sudah ada pada model tersimpan. Garis dan teks native; anotasi tidak asosiatif. Ekspor berikut memperlihatkan isi lembar.</p><div class="downloads">'+native_links+'</div></details></section>\n<section id="analisis">',1)
 template=template.replace('<strong>8 X</strong><span>pengaku global dipertahankan</span>','<strong>10 X</strong><span>6 belakang · 2 sisi · 2 horizontal</span>').replace('PDF 4 lembar','PDF 6 lembar')
 template=template.replace('Model Revit native masih R03 karena koneksi Geopogo tidak tersedia; model web menampilkan usulan tangga R04.','Model tersimpan:165RHS,20diagonal,176bagian tangga3mm dan310bagian penutup2mm. Model web mengikuti komponen tersebut; penyangga tambahan dan sambungan pada RAB masih usulan.').replace('Data takikan beton belum tersedia. Blank dan gambar tangga memakai batas luar geometri; lakukan kupon tekuk dan ukur bidang khusus sebelum produksi.','Takikan tangga mengikuti outline IFC yang luasnya cocok dengan audit Revit. Penutup diberi celah3mm terhadap empat kolom beton; ukuran produksi mengikuti pengukuran dan kupon tekuk.')
 template=template.replace('Angka Rp123 pada toko cat tidak dipakai sebagai harga karena tampil sebagai placeholder; biaya cat memakai allowance yang jelas.','Harga cat dan hardware yang belum memiliki penawaran tertulis ditampilkan sebagai allowance.')
 (dist/'r04.html').write_text(template.replace('CARDS',cards).replace('SOURCES',sources),encoding='utf8')
 for name in ['style.css','app.js']:(dist/'assets/r04'/name).write_bytes((ROOT/('r04_'+name)).read_bytes())
 for page in ['index.html','tools.html']:
  p=dist/page;s=BeautifulSoup(p.read_text(encoding='utf8'),'html.parser')
  if page=='index.html':
   target=s.select_one('.project-links');target.insert(0,BeautifulSoup('<a href="r04.html">Tangga 3 mm · Detail & RAB R04 ↗</a>','html.parser'))
   s.select_one('#archive-menu nav').append(BeautifulSoup('<a href="r04.html">07 <span>Tangga & RAB R04</span>↗</a>','html.parser'))
  else:
   s.select_one('main').insert(0,BeautifulSoup('<p class="r04-banner"><a href="r04.html">R04 / Tangga pelat tekuk 3 mm · Gambar sambungan · RAB all-in ↗</a></p>','html.parser'))
   text=s.select_one('#tiga-d .lede')
   if text:text.string='R04:165RHS dan10setX;56bidang tangga3mm serta310bagian penutup2mm mengikuti model tersimpan. Dek tetap4mm. Matikan lapisan penutup untuk memeriksa rangka. Detail sambungan usulan tersedia di RAB dan gambar R04.'
   for el in s.select('.pitch-kicker span,.look-mast a,.look-footer p'):
    if el.string:el.string=el.string.replace('R03','R04')
   metrics=s.select('.pitch-metrics b')
   if metrics:metrics[-1].string='10 X'
   figure=s.select_one('.hero-drawing')
   if figure:
    figure.select_one('img')['src']='assets/r04/T-06.svg';figure.select_one('img')['alt']='Rencana10setX revisi R04'
    figure.select_one('figcaption').clear();figure.select_one('figcaption').append(BeautifulSoup('<span>R04 / POSISI BRACING</span><span>T-06</span>','html.parser'))
    for el,val in zip(figure.select('.hero-drawing-info b'),['165','80','20']):el.string=val
   stock=len(data['main_stock']);cost=stock*434500
   articles=s.select('#material .material-grid article')
   if len(articles)>1:
    articles[1].select('p')[-1].string=f'RAB R04 menggabungkan rangka165elemen,80kolom dan usulan penyangga tangga dalam{stock}stok6m. Buka RAB untuk dasar biaya.'
   budget=s.select_one('.pitch-budget-grid')
   if budget:
    budget.clear();budget.append(BeautifulSoup('<div><span>RAB TERPILIH / R04</span><b>Material + jasa</b><p>Pelat4/3/2mm, sambungan, cat, upah, logistik, overhead dan laba.</p></div><div><p>Rincian terbaru memakai ID model R04, harga satuan editable dan toggle jasa Rp6.000/kg.</p><a href="r04.html#rab">Buka RAB all-in R04 ↗</a></div>','html.parser'))
   old_gallery=s.select_one('.gallery-help')
   if old_gallery:old_gallery.clear();old_gallery.append(BeautifulSoup('Arsip R03 · LOD200. <a href="r04.html#gambar">Buka6lembar revisi R04: tangga, penutup dan posisi X ↗</a>','html.parser'))
   cut=s.select_one('#potong .lede')
   if cut:cut.string='Pola75stok pada lampiran ini adalah arsip R03. Rangka berubah menjadi165elemen; gunakan daftar potong R04 yang menghapus diagonal lama dan memasukkan penggantinya.'
   for sel in ['#boq .lede','#penawaran .lede']:
    el=s.select_one(sel)
    if el:el.clear();el.append(BeautifulSoup('Kalkulator kuantitas model. <a href="r04.html#rab">Gunakan RAB R04 untuk seluruh material, sambungan, upah, cat dan penawaran anggaran.</a>','html.parser'))
  p.write_text(str(s),encoding='utf8')
